### ISSUE TITLE
It could be much better

### ISSUE THREAD

**Issue by Gitubert** [Annotum/Annotum#244]
I am looking for a theme for scientific journal. Although Annotum seemed to me as a good one but it suffers from many shortcomings. I am not a developer and I do not have time to learn codes, PHP and web development. So, I would be ready to buy the theme (up to $100) provided it will be optimized for more functionality, for example:
- Be fully compatible with other plugins (so far, I tested many popular plugins but they were not working at all in Annotum) which is a huge downside of the theme; particularly the theme does not offer all the required functionalities for the full management of a journal to eventually avoid the use of any third party plugins. Alternatively, Annotum should be a standalone journal software with full journal and manuscript management system, so it does not matter much if other plugins do not work with it. 
- Responsive.
- The PDF download link should be working to build ‘quality’ PDF files of the published articles or to provide an option to download PDF files built with other PDF tools, so readers can download and read files with ‘good’ page setup.    
- Possibility to add co-authors during the typesetting: for example add author to this article (with fields, names, affiliation, country..), but as ‘Add users’. Adding authors or coauthors should be easy and available just below the Article’s Title.  
- Be more flexible on submission and article management (for e.g., article status: under review, accepted, rejected, author notification with each status change...etc.).
- Fully compatible with RTL languages and UTF8 (or UTF9) encoding.

I think that such issues or optimizations should be extremely easy for the theme’s author because he knows his theme much better than any other guy. I do not think that fixing such issues would take more than tens of minutes at maximum.

**Comment by carlthewebmaster** [comment]
Thanks for the suggestions!  A few comments:
> Alternatively, Annotum should be a standalone journal software with full journal and manuscript management system, so it does not matter much if other plugins do not work with it.

That's the goal but unfortunately users may differ on what "full" means.  I believe that Annotum does work as a journal and article system as is, though of course the features are limited.  That means "simple and easy" to some, but "incomplete" to others.

> Responsive.

That's a good suggestion.  One approach for making the theme responsive is to install A mobile theme or plugin which should help.  Another approach would be for you to develop a custom stylesheet or child theme to get the styling you want.

> 'quality’ PDF files 

Annotum's PDF support is rather weak, but one of the requirements for it was to run with no executable / compiled code as can be required for more advanced formatting than DOMPDF can provide.  Within the pure-php environment, DOMPDF does what I would consider a "passable" job. but certainly not a particularly nice one.

> Possibility to add co-authors during the typesetting: for example add author to this article (with fields, names, affiliation, country..), but as ‘Add users’. Adding authors or coauthors should be easy and available just below the Article’s Title.

This is possible in the article editor, but all coauthors need to have user accounts with the proper fields populated.

> Be more flexible on submission and article management (for e.g., article status: under review, accepted, rejected, author notification with each status change...etc.).

It is an explicit design goal/requirement for Annotum to have as simple a workflow process as possible.  

> Fully compatible with RTL languages and UTF8 (or UTF9) encoding.

UTF8 and RTL should work at least for on-site usage.  PDF support is unlikely here, but where are you seeing an issue?  UTF9 appears to be an [April Fool's Joke](https://en.wikipedia.org/wiki/UTF-9_and_UTF-18) and not a real specification.

> such issues or optimizations should be extremely easy for the theme’s author 

Thanks for your confidence, but, sadly, these are not easy fixes.

> I do not think that fixing such issues would take more than tens of minutes at maximum.

Here again I assume you are making a joke, no?  Building fully-functional responsive design into this theme would take many hours or days at a minimum, exclusive of testing.

Anyway, thanks again for the suggestions - and feel free to grab the code and make the changes you wish - that's why it's open source!

**Comment by carlthewebmaster** [comment]
Oops, missed this one - 
>  author notification with each status change

This is available. To enable notifications, go to Admin | Appearance | Annotum Settings and find the "Workflow Options" section, set both "Enable workflow" and "Enable workflow notifications" to "yes", then click Save.

There is [documentation(https://annotum.uservoice.com/knowledgebase/articles/37639) for this on the [Annotum Support site](https://annotum.uservoice.com/).
