### ISSUE TITLE
Multi-level nav menu item do not display

### ISSUE THREAD

**Issue by profnimrod** [Annotum/Annotum#252]
I Have 700+ articles that are organized into 50+ journal 'issues'.  At the moment the 'issues' appear in a single level nav list (see https://journal.emergentpublications.com/ under Issues).  Given that the list is going to be rather long I'd rather organize the issues into volumes (comprising 4 issues), and have the issues appear when the user hovers over the volume.  However, when I try this the lower 'issue' levels are not displayed.  I've tried using third party nav plug-ins but they do not work.  Is this an Annotum limitation?  If so, how can I enable multi-level nav drop downs?

**Comment by carlthewebmaster** [comment]
Unfortunately, Annotum's design only supports two menu levels in the top navigation menu bar. It is possible to enable additional menu levels (to display them) by modifying the "depth" parameter set on [line 195 of the 'functions.php' file](https://github.com/Annotum/Annotum/blob/master/annotum-base/functions.php#L195) (`wp-content/themes/annotum-base/functions.php`); you can set it to 3 or 4 to show additional menu levels. 

However please note that the 'deeper' levels won't display any differently than the first submenu level, because the Annotum style sheet doesn't provide a specific format for the additional levels. You could modify the CSS to support that, of course.

**Comment by profnimrod** [comment]
Thanks for the guidance Carl.  Your suggestion plus some CSS works OK.. Here's my first stab at the CSS in case it proves useful for anyone:

`#site-nav ul.sub-menu li.menu-item ul.sub-menu {
	position:relative;
	margin-left: 50px !important;
	width: 400px !important;
	display: none !important;
	z-index: 999999 !important;
}

#site-nav ul.sub-menu li.menu-item {
	z-index: 999999 !important;
}

#site-nav ul.sub-menu li.menu-item ul.sub-menu li.menu-item a:before {
	content: "\00BB \0020";
}

#site-nav ul.sub-menu li.menu-item ul.sub-menu li.menu-item {
	background-color: red !important;
}`

I'm having some z-index issues... but nothing a bit of time and effort won't fix.
